export interface SongNote {
    note: string;
    duration: number; // in seconds, or relative beat
    lyric?: string;
}

export interface Song {
    id: string;
    title: string;
    titleHi?: string;
    artist?: string;
    difficulty: "easy" | "medium" | "hard";
    instrument: string;
    notes: SongNote[];
    description?: string;
    descriptionHi?: string;
    tags: string[];
}

export const SONGS: Song[] = [
    // ===== INDIAN PATRIOTIC SONGS =====
    {
        id: "jana-gana-mana",
        title: "Jana Gana Mana",
        titleHi: "जन गण मन",
        artist: "Rabindranath Tagore",
        difficulty: "medium",
        instrument: "harmonium",
        description: "The National Anthem of India - Correct Sargam",
        descriptionHi: "भारत का राष्ट्रगान - सही सरगम",
        tags: ["patriotic", "anthem", "india"],
        notes: [
            // जन गण मन अधिनायक जय हे (SR GG GG GGGGG RG M)
            { note: "S", duration: 0.5, lyric: "Ja" },
            { note: "R", duration: 0.5, lyric: "na" },
            { note: "G", duration: 0.5, lyric: "Ga" },
            { note: "G", duration: 0.5, lyric: "na" },
            { note: "G", duration: 0.5, lyric: "Ma" },
            { note: "G", duration: 0.5, lyric: "na" },
            { note: "G", duration: 0.3, lyric: "A" },
            { note: "G", duration: 0.3, lyric: "dhi" },
            { note: "G", duration: 0.3, lyric: "naa" },
            { note: "G", duration: 0.3, lyric: "ya" },
            { note: "G", duration: 0.3, lyric: "k" },
            { note: "R", duration: 0.5, lyric: "Ja" },
            { note: "G", duration: 0.5, lyric: "ya" },
            { note: "M", duration: 1, lyric: "He" },

            // भारत भाग्य विधाता (GGG RRR .N RS)
            { note: "G", duration: 0.3, lyric: "Bhaa" },
            { note: "G", duration: 0.3, lyric: "ra" },
            { note: "G", duration: 0.5, lyric: "ta" },
            { note: "R", duration: 0.3, lyric: "Bhaag" },
            { note: "R", duration: 0.3, lyric: "ya" },
            { note: "R", duration: 0.5, lyric: "" },
            { note: ".N", duration: 0.5, lyric: "Vi" },
            { note: "R", duration: 0.5, lyric: "dhaa" },
            { note: "S", duration: 1, lyric: "taa" },

            // पंजाब सिंध गुजरात मराठा (SPP PP PPPP PMDP)
            { note: "S", duration: 0.5, lyric: "Pun" },
            { note: "P", duration: 0.3, lyric: "jab" },
            { note: "P", duration: 0.3, lyric: "" },
            { note: "P", duration: 0.3, lyric: "Sindh" },
            { note: "P", duration: 0.3, lyric: "" },
            { note: "P", duration: 0.3, lyric: "Gu" },
            { note: "P", duration: 0.3, lyric: "ja" },
            { note: "P", duration: 0.3, lyric: "raa" },
            { note: "P", duration: 0.3, lyric: "t" },
            { note: "P", duration: 0.3, lyric: "Ma" },
            { note: "M", duration: 0.3, lyric: "raa" },
            { note: "D", duration: 0.3, lyric: "tha" },
            { note: "P", duration: 0.5, lyric: "" },

            // द्रविड़ उत्कल बंगा (MMM GGG RMG)
            { note: "M", duration: 0.3, lyric: "Draa" },
            { note: "M", duration: 0.3, lyric: "vi" },
            { note: "M", duration: 0.5, lyric: "da" },
            { note: "G", duration: 0.3, lyric: "Ut" },
            { note: "G", duration: 0.3, lyric: "ka" },
            { note: "G", duration: 0.5, lyric: "la" },
            { note: "R", duration: 0.3, lyric: "Ban" },
            { note: "M", duration: 0.3, lyric: "" },
            { note: "G", duration: 1, lyric: "gaa" },

            // विंध्य हिमाचल यमुना गंगा (GG GGGR PPP MM)
            { note: "G", duration: 0.3, lyric: "Vin" },
            { note: "G", duration: 0.5, lyric: "dhya" },
            { note: "G", duration: 0.3, lyric: "Hi" },
            { note: "G", duration: 0.3, lyric: "maa" },
            { note: "G", duration: 0.3, lyric: "cha" },
            { note: "R", duration: 0.5, lyric: "la" },
            { note: "P", duration: 0.3, lyric: "Ya" },
            { note: "P", duration: 0.3, lyric: "mu" },
            { note: "P", duration: 0.5, lyric: "na" },
            { note: "M", duration: 0.5, lyric: "Gan" },
            { note: "M", duration: 1, lyric: "gaa" },

            // उच्छल जलधि तरंग (GGG RRR .NRS)
            { note: "G", duration: 0.3, lyric: "Uch" },
            { note: "G", duration: 0.3, lyric: "chha" },
            { note: "G", duration: 0.5, lyric: "la" },
            { note: "R", duration: 0.3, lyric: "Ja" },
            { note: "R", duration: 0.3, lyric: "la" },
            { note: "R", duration: 0.5, lyric: "dhi" },
            { note: ".N", duration: 0.3, lyric: "Ta" },
            { note: "R", duration: 0.3, lyric: "ran" },
            { note: "S", duration: 1, lyric: "ga" },

            // तव शुभ नामे जागे (SR GG GG RGM)
            { note: "S", duration: 0.3, lyric: "Ta" },
            { note: "R", duration: 0.5, lyric: "va" },
            { note: "G", duration: 0.3, lyric: "Shubh" },
            { note: "G", duration: 0.5, lyric: "" },
            { note: "G", duration: 0.3, lyric: "Naa" },
            { note: "G", duration: 0.5, lyric: "me" },
            { note: "R", duration: 0.3, lyric: "Jaa" },
            { note: "G", duration: 0.3, lyric: "" },
            { note: "M", duration: 1, lyric: "ge" },

            // तव शुभ आशिष मांगे (GM PP PMG RGM)
            { note: "G", duration: 0.3, lyric: "Ta" },
            { note: "M", duration: 0.5, lyric: "va" },
            { note: "P", duration: 0.3, lyric: "Shubh" },
            { note: "P", duration: 0.5, lyric: "" },
            { note: "P", duration: 0.3, lyric: "Aa" },
            { note: "M", duration: 0.3, lyric: "shi" },
            { note: "G", duration: 0.5, lyric: "sha" },
            { note: "R", duration: 0.3, lyric: "Maan" },
            { note: "G", duration: 0.3, lyric: "" },
            { note: "M", duration: 1, lyric: "ge" },

            // गाहे तव जय गाथा (GG RR R .NRS)
            { note: "G", duration: 0.3, lyric: "Gaa" },
            { note: "G", duration: 0.5, lyric: "he" },
            { note: "R", duration: 0.3, lyric: "Ta" },
            { note: "R", duration: 0.5, lyric: "va" },
            { note: "R", duration: 0.5, lyric: "Ja" },
            { note: ".N", duration: 0.3, lyric: "ya" },
            { note: "R", duration: 0.3, lyric: "Gaa" },
            { note: "S", duration: 1, lyric: "thaa" },

            // जन गण मंगल दायक जय हे (PP PP PPP PPP MD P)
            { note: "P", duration: 0.3, lyric: "Ja" },
            { note: "P", duration: 0.5, lyric: "na" },
            { note: "P", duration: 0.3, lyric: "Ga" },
            { note: "P", duration: 0.5, lyric: "na" },
            { note: "P", duration: 0.3, lyric: "Man" },
            { note: "P", duration: 0.3, lyric: "ga" },
            { note: "P", duration: 0.3, lyric: "la" },
            { note: "P", duration: 0.3, lyric: "Daa" },
            { note: "P", duration: 0.3, lyric: "ya" },
            { note: "P", duration: 0.3, lyric: "ka" },
            { note: "M", duration: 0.5, lyric: "Ja" },
            { note: "D", duration: 0.5, lyric: "ya" },
            { note: "P", duration: 1, lyric: "He" },

            // भारत भाग्य विधाता (MMM GGG RMG)
            { note: "M", duration: 0.3, lyric: "Bhaa" },
            { note: "M", duration: 0.3, lyric: "ra" },
            { note: "M", duration: 0.5, lyric: "ta" },
            { note: "G", duration: 0.3, lyric: "Bhaag" },
            { note: "G", duration: 0.3, lyric: "ya" },
            { note: "G", duration: 0.5, lyric: "" },
            { note: "R", duration: 0.3, lyric: "Vi" },
            { note: "M", duration: 0.3, lyric: "dhaa" },
            { note: "G", duration: 1, lyric: "taa" },

            // जय हे, जय हे, जय हे (NN S. ND N DP D)
            { note: "N", duration: 0.5, lyric: "Ja" },
            { note: "N", duration: 0.5, lyric: "ya" },
            { note: "S'", duration: 1, lyric: "He" },
            { note: "N", duration: 0.5, lyric: "Ja" },
            { note: "D", duration: 0.5, lyric: "ya" },
            { note: "N", duration: 1, lyric: "He" },
            { note: "D", duration: 0.5, lyric: "Ja" },
            { note: "P", duration: 0.5, lyric: "ya" },
            { note: "D", duration: 1, lyric: "He" },

            // जय जय जय जय हे (SS RR GG RG M) - using middle octave for harmonium
            { note: "S'", duration: 0.5, lyric: "Ja" },
            { note: "S'", duration: 0.5, lyric: "ya" },
            { note: "N", duration: 0.5, lyric: "Ja" },
            { note: "N", duration: 0.5, lyric: "ya" },
            { note: "D", duration: 0.5, lyric: "Ja" },
            { note: "D", duration: 0.5, lyric: "ya" },
            { note: "P", duration: 0.3, lyric: "Ja" },
            { note: "M", duration: 0.3, lyric: "ya" },
            { note: "G", duration: 1.5, lyric: "He" }
        ]
    },
    {
        id: "vande-mataram",
        title: "Vande Mataram",
        titleHi: "वंदे मातरम्",
        artist: "Bankim Chandra Chattopadhyay",
        difficulty: "medium",
        instrument: "harmonium",
        description: "National Song of India - Slower version with correct sargam",
        descriptionHi: "भारत का राष्ट्रीय गीत - सही सरगम के साथ",
        tags: ["patriotic", "national song", "india"],
        notes: [
            // वंदे मातरम् [Sa-Re]–[MaPaMaPa—]
            { note: "S", duration: 0.5, lyric: "Van" },
            { note: "R", duration: 0.5, lyric: "de" },
            { note: "M", duration: 0.5, lyric: "Maa" },
            { note: "P", duration: 0.5, lyric: "ta" },
            { note: "M", duration: 0.5, lyric: "" },
            { note: "P", duration: 1.5, lyric: "ram" },

            // सुजलाम् सुफलाम् [Ma-Pa]–[NiSANiSA]
            { note: "M", duration: 0.5, lyric: "Su" },
            { note: "P", duration: 0.5, lyric: "ja" },
            { note: "N", duration: 0.5, lyric: "laam" },
            { note: "S'", duration: 0.5, lyric: "Su" },
            { note: "N", duration: 0.5, lyric: "pha" },
            { note: "S'", duration: 1, lyric: "laam" },

            // मलयज शीतलाम् [SARENi_–DhaPa-] [PaDhaMa–GaRe-]
            { note: "S'", duration: 0.5, lyric: "Ma" },
            { note: "R", duration: 0.5, lyric: "la" },
            { note: "N", duration: 0.5, lyric: "ya" },
            { note: "D", duration: 0.5, lyric: "ja" },
            { note: "P", duration: 0.5, lyric: "Shee" },
            { note: "P", duration: 0.5, lyric: "ta" },
            { note: "D", duration: 0.5, lyric: "laam" },
            { note: "M", duration: 0.5, lyric: "" },
            { note: "G", duration: 0.5, lyric: "" },
            { note: "R", duration: 0.5, lyric: "" },

            // शस्यश्यामलाम् मातरम् [RePaMaMa–]Ga-[ReGa]Sa–]
            { note: "R", duration: 0.5, lyric: "Sa" },
            { note: "P", duration: 0.5, lyric: "sya" },
            { note: "M", duration: 0.5, lyric: "shyaa" },
            { note: "M", duration: 1, lyric: "ma" },
            { note: "G", duration: 0.5, lyric: "laam" },
            { note: "R", duration: 0.5, lyric: "Maa" },
            { note: "G", duration: 0.5, lyric: "ta" },
            { note: "S", duration: 1.5, lyric: "ram" },

            // वंदे मातरम् [Sa-Re] [MaPaMaPa–][PaNi_ DhaPa–]
            { note: "S", duration: 0.5, lyric: "Van" },
            { note: "R", duration: 0.5, lyric: "de" },
            { note: "M", duration: 0.5, lyric: "Maa" },
            { note: "P", duration: 0.5, lyric: "ta" },
            { note: "M", duration: 0.5, lyric: "" },
            { note: "P", duration: 1, lyric: "ram" },
            { note: "P", duration: 0.5, lyric: "" },
            { note: "N", duration: 0.5, lyric: "" },
            { note: "D", duration: 0.5, lyric: "" },
            { note: "P", duration: 1, lyric: "" },

            // शुभ्रज्योत्स्ना पुलकितयामिनीम् [Ma-Pa-][Ni-Ni -][NiNiSANiSA–Ni SA]
            { note: "M", duration: 0.5, lyric: "Shubh" },
            { note: "P", duration: 0.5, lyric: "ra" },
            { note: "N", duration: 0.5, lyric: "jyots" },
            { note: "N", duration: 0.5, lyric: "naa" },
            { note: "N", duration: 0.3, lyric: "Pu" },
            { note: "N", duration: 0.3, lyric: "la" },
            { note: "S'", duration: 0.3, lyric: "ki" },
            { note: "N", duration: 0.3, lyric: "ta" },
            { note: "S'", duration: 1, lyric: "yaa" },
            { note: "N", duration: 0.5, lyric: "mi" },
            { note: "S'", duration: 1, lyric: "neem" },

            // पुल्लकुसुमित द्रुमदल शोभिनीम् [Ni-NiNiSANiSA-][SARESANi] [Ni_ Dha Ni_ Dha-Pa–]
            { note: "N", duration: 0.3, lyric: "Pul" },
            { note: "N", duration: 0.3, lyric: "la" },
            { note: "N", duration: 0.3, lyric: "ku" },
            { note: "S'", duration: 0.3, lyric: "su" },
            { note: "N", duration: 0.3, lyric: "mi" },
            { note: "S'", duration: 0.5, lyric: "ta" },
            { note: "S'", duration: 0.3, lyric: "dru" },
            { note: "N", duration: 0.3, lyric: "ma" },
            { note: "S'", duration: 0.3, lyric: "dal" },
            { note: "N", duration: 0.5, lyric: "sho" },
            { note: "N", duration: 0.3, lyric: "bhi" },
            { note: "D", duration: 0.3, lyric: "neem" },
            { note: "N", duration: 0.3, lyric: "" },
            { note: "D", duration: 0.5, lyric: "" },
            { note: "P", duration: 1, lyric: "" },

            // सुहासिनीं सुमधुर भाषिणीम् [ReReMaGaRe–][ReNi_ DhaNi_Dha Pa-Dha Pa–]
            { note: "R", duration: 0.3, lyric: "Su" },
            { note: "R", duration: 0.3, lyric: "haa" },
            { note: "M", duration: 0.3, lyric: "si" },
            { note: "G", duration: 0.3, lyric: "neem" },
            { note: "R", duration: 0.5, lyric: "" },
            { note: "R", duration: 0.3, lyric: "Su" },
            { note: "N", duration: 0.3, lyric: "ma" },
            { note: "D", duration: 0.3, lyric: "dhu" },
            { note: "N", duration: 0.3, lyric: "ra" },
            { note: "D", duration: 0.5, lyric: "bhaa" },
            { note: "P", duration: 0.5, lyric: "shi" },
            { note: "D", duration: 0.5, lyric: "neem" },
            { note: "P", duration: 1, lyric: "" },

            // सुखदां वरदां मातरम् [Ma-Pa-Ni-Ni NiNi-] [Ni SA–Ni SA–]
            { note: "M", duration: 0.5, lyric: "Su" },
            { note: "P", duration: 0.5, lyric: "kha" },
            { note: "N", duration: 0.5, lyric: "daam" },
            { note: "N", duration: 0.3, lyric: "Va" },
            { note: "N", duration: 0.3, lyric: "ra" },
            { note: "N", duration: 0.5, lyric: "daam" },
            { note: "N", duration: 0.5, lyric: "Maa" },
            { note: "S'", duration: 1, lyric: "ta" },
            { note: "N", duration: 0.5, lyric: "" },
            { note: "S'", duration: 1.5, lyric: "ram" },

            // वंदे मातरम् [Ma-Pa–][NiSANiSA]
            { note: "M", duration: 0.5, lyric: "Van" },
            { note: "P", duration: 1, lyric: "de" },
            { note: "N", duration: 0.5, lyric: "Maa" },
            { note: "S'", duration: 0.5, lyric: "ta" },
            { note: "N", duration: 0.5, lyric: "" },
            { note: "S'", duration: 1.5, lyric: "ram" }
        ]
    },
    {
        id: "saare-jahan-se-achha",
        title: "Sare Jahan Se Achha",
        titleHi: "सारे जहाँ से अच्छा",
        artist: "Muhammad Iqbal",
        difficulty: "medium",
        instrument: "harmonium",
        description: "Patriotic song celebrating India - Correct Sargam",
        descriptionHi: "भारत की सुंदरता का गुणगान - सही सरगम",
        tags: ["patriotic", "classic", "india"],
        notes: [
            // ===== Part 1 - सारे जहाँ से अच्छा =====
            // ग~ गरे सा रे~ *नि सा~ सा~ (saare jahaan se achcha)
            { note: "G", duration: 1, lyric: "Saa" },
            { note: "G", duration: 0.3, lyric: "" },
            { note: "R", duration: 0.5, lyric: "re" },
            { note: "S", duration: 0.5, lyric: "Ja" },
            { note: "R", duration: 1, lyric: "haan" },
            { note: ".N", duration: 0.5, lyric: "Se" },
            { note: "S", duration: 1, lyric: "Ach" },
            { note: "S", duration: 1, lyric: "cha" },

            // Filler: सा *नि *ध *प
            { note: "S", duration: 0.5, lyric: "" },
            { note: ".N", duration: 0.5, lyric: "" },
            { note: ".D", duration: 0.5, lyric: "" },
            { note: ".P", duration: 0.5, lyric: "" },

            // *प *ध सा रेग मग~ ग~ (hindustan hamaara)
            { note: ".P", duration: 0.3, lyric: "Hin" },
            { note: ".D", duration: 0.3, lyric: "" },
            { note: "S", duration: 0.5, lyric: "du" },
            { note: "R", duration: 0.3, lyric: "" },
            { note: "G", duration: 0.5, lyric: "staan" },
            { note: "M", duration: 0.3, lyric: "Ha" },
            { note: "G", duration: 1, lyric: "maa" },
            { note: "G", duration: 1, lyric: "raa" },

            // रेमगरेसा (hamaara)
            { note: "R", duration: 0.3, lyric: "Ha" },
            { note: "M", duration: 0.3, lyric: "maa" },
            { note: "G", duration: 0.3, lyric: "" },
            { note: "R", duration: 0.3, lyric: "" },
            { note: "S", duration: 1, lyric: "raa" },

            // ग~ रे सा रे *नि सा~ सा~ (saare jahaan se achcha - repeat)
            { note: "G", duration: 1, lyric: "Saa" },
            { note: "R", duration: 0.5, lyric: "re" },
            { note: "S", duration: 0.5, lyric: "Ja" },
            { note: "R", duration: 0.5, lyric: "haan" },
            { note: ".N", duration: 0.5, lyric: "Se" },
            { note: "S", duration: 1, lyric: "Ach" },
            { note: "S", duration: 1, lyric: "cha" },

            // ===== Part 2 - हम बुलबुलें हैं =====
            // गम प~ पप (hum bul bule)
            { note: "G", duration: 0.3, lyric: "Hum" },
            { note: "M", duration: 0.5, lyric: "" },
            { note: "P", duration: 1, lyric: "Bul" },
            { note: "P", duration: 0.3, lyric: "bu" },
            { note: "P", duration: 0.3, lyric: "le" },

            // ग~ मध प~~ (hai is ki)
            { note: "G", duration: 1, lyric: "Hain" },
            { note: "M", duration: 0.3, lyric: "Is" },
            { note: "D", duration: 0.5, lyric: "" },
            { note: "P", duration: 1.5, lyric: "ki" },

            // गम प~ मग (ye gul sitaa)
            { note: "G", duration: 0.3, lyric: "Ye" },
            { note: "M", duration: 0.5, lyric: "" },
            { note: "P", duration: 1, lyric: "Gul" },
            { note: "M", duration: 0.3, lyric: "lis" },
            { note: "G", duration: 0.5, lyric: "taan" },

            // रेसा~~ सा सासा *नि *ध *प (hamaara hamaara)
            { note: "R", duration: 0.3, lyric: "Ha" },
            { note: "S", duration: 1.5, lyric: "maa" },
            { note: "S", duration: 0.5, lyric: "raa" },
            { note: "S", duration: 0.3, lyric: "Ha" },
            { note: "S", duration: 0.3, lyric: "maa" },
            { note: ".N", duration: 0.3, lyric: "raa" },
            { note: ".D", duration: 0.3, lyric: "" },
            { note: ".P", duration: 0.5, lyric: "" },

            // ===== Part 3 - Repeat =====
            // ग~~ रे सा रे *नि सा~ सा (saare jahaan se achcha)
            { note: "G", duration: 1.5, lyric: "Saa" },
            { note: "R", duration: 0.5, lyric: "re" },
            { note: "S", duration: 0.5, lyric: "Ja" },
            { note: "R", duration: 0.5, lyric: "haan" },
            { note: ".N", duration: 0.5, lyric: "Se" },
            { note: "S", duration: 1, lyric: "Ach" },
            { note: "S", duration: 1, lyric: "cha" },

            // Filler: सा *नि *ध *प
            { note: "S", duration: 0.5, lyric: "" },
            { note: ".N", duration: 0.5, lyric: "" },
            { note: ".D", duration: 0.5, lyric: "" },
            { note: ".P", duration: 0.5, lyric: "" },

            // *प *ध सा रेग मग~ ग~ रेमगरेसा (Hindustan hamaara hamaara)
            { note: ".P", duration: 0.3, lyric: "Hin" },
            { note: ".D", duration: 0.3, lyric: "" },
            { note: "S", duration: 0.5, lyric: "du" },
            { note: "R", duration: 0.3, lyric: "" },
            { note: "G", duration: 0.5, lyric: "staan" },
            { note: "M", duration: 0.3, lyric: "Ha" },
            { note: "G", duration: 1, lyric: "maa" },
            { note: "G", duration: 1, lyric: "raa" },
            { note: "R", duration: 0.3, lyric: "Ha" },
            { note: "M", duration: 0.3, lyric: "maa" },
            { note: "G", duration: 0.3, lyric: "" },
            { note: "R", duration: 0.3, lyric: "" },
            { note: "S", duration: 1, lyric: "raa" },

            // Final: ग~ रे सा रे *नि सा~ सा~
            { note: "G", duration: 1, lyric: "Saa" },
            { note: "R", duration: 0.5, lyric: "re" },
            { note: "S", duration: 0.5, lyric: "Ja" },
            { note: "R", duration: 0.5, lyric: "haan" },
            { note: ".N", duration: 0.5, lyric: "Se" },
            { note: "S", duration: 1, lyric: "Ach" },
            { note: "S", duration: 1.5, lyric: "cha" }
        ]
    },

    // ===== CLASSIC & KIDS SONGS (COMPLETE VERSIONS) =====
    {
        id: "happy-birthday",
        title: "Happy Birthday",
        titleHi: "जन्मदिन मुबारक",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "The classic birthday song that everyone should know!",
        descriptionHi: "क्लासिक जन्मदिन गाना जो हर किसी को आना चाहिए!",
        tags: ["classic", "celebration", "kids"],
        notes: [
            // Happy birthday to you
            { note: "C4", duration: 0.75, lyric: "Hap" },
            { note: "C4", duration: 0.25, lyric: "py" },
            { note: "D4", duration: 1, lyric: "birth" },
            { note: "C4", duration: 1, lyric: "day" },
            { note: "F4", duration: 1, lyric: "to" },
            { note: "E4", duration: 2, lyric: "you" },
            // Happy birthday to you
            { note: "C4", duration: 0.75, lyric: "Hap" },
            { note: "C4", duration: 0.25, lyric: "py" },
            { note: "D4", duration: 1, lyric: "birth" },
            { note: "C4", duration: 1, lyric: "day" },
            { note: "G4", duration: 1, lyric: "to" },
            { note: "F4", duration: 2, lyric: "you" },
            // Happy birthday dear [name]
            { note: "C4", duration: 0.75, lyric: "Hap" },
            { note: "C4", duration: 0.25, lyric: "py" },
            { note: "C5", duration: 1, lyric: "birth" },
            { note: "A4", duration: 1, lyric: "day" },
            { note: "F4", duration: 1, lyric: "dear" },
            { note: "E4", duration: 1, lyric: "friend" },
            { note: "D4", duration: 1, lyric: "" },
            // Happy birthday to you
            { note: "A#4", duration: 0.75, lyric: "Hap" },
            { note: "A#4", duration: 0.25, lyric: "py" },
            { note: "A4", duration: 1, lyric: "birth" },
            { note: "F4", duration: 1, lyric: "day" },
            { note: "G4", duration: 1, lyric: "to" },
            { note: "F4", duration: 2, lyric: "you" }
        ]
    },
    {
        id: "twinkle-twinkle",
        title: "Twinkle Twinkle Little Star",
        titleHi: "ट्विंकल ट्विंकल लिटिल स्टार",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "A perfect first song for beginners.",
        descriptionHi: "शुरुआत के लिए सबसे अच्छा गाना।",
        tags: ["nursery", "kids", "beginner"],
        notes: [
            // Twinkle twinkle little star
            { note: "C4", duration: 1, lyric: "Twin" },
            { note: "C4", duration: 1, lyric: "kle" },
            { note: "G4", duration: 1, lyric: "twin" },
            { note: "G4", duration: 1, lyric: "kle" },
            { note: "A4", duration: 1, lyric: "lit" },
            { note: "A4", duration: 1, lyric: "tle" },
            { note: "G4", duration: 2, lyric: "star" },
            // How I wonder what you are
            { note: "F4", duration: 1, lyric: "How" },
            { note: "F4", duration: 1, lyric: "I" },
            { note: "E4", duration: 1, lyric: "won" },
            { note: "E4", duration: 1, lyric: "der" },
            { note: "D4", duration: 1, lyric: "what" },
            { note: "D4", duration: 1, lyric: "you" },
            { note: "C4", duration: 2, lyric: "are" },
            // Up above the world so high
            { note: "G4", duration: 1, lyric: "Up" },
            { note: "G4", duration: 1, lyric: "a" },
            { note: "F4", duration: 1, lyric: "bove" },
            { note: "F4", duration: 1, lyric: "the" },
            { note: "E4", duration: 1, lyric: "world" },
            { note: "E4", duration: 1, lyric: "so" },
            { note: "D4", duration: 2, lyric: "high" },
            // Like a diamond in the sky
            { note: "G4", duration: 1, lyric: "Like" },
            { note: "G4", duration: 1, lyric: "a" },
            { note: "F4", duration: 1, lyric: "dia" },
            { note: "F4", duration: 1, lyric: "mond" },
            { note: "E4", duration: 1, lyric: "in" },
            { note: "E4", duration: 1, lyric: "the" },
            { note: "D4", duration: 2, lyric: "sky" },
            // Twinkle twinkle little star (repeat)
            { note: "C4", duration: 1, lyric: "Twin" },
            { note: "C4", duration: 1, lyric: "kle" },
            { note: "G4", duration: 1, lyric: "twin" },
            { note: "G4", duration: 1, lyric: "kle" },
            { note: "A4", duration: 1, lyric: "lit" },
            { note: "A4", duration: 1, lyric: "tle" },
            { note: "G4", duration: 2, lyric: "star" },
            // How I wonder what you are
            { note: "F4", duration: 1, lyric: "How" },
            { note: "F4", duration: 1, lyric: "I" },
            { note: "E4", duration: 1, lyric: "won" },
            { note: "E4", duration: 1, lyric: "der" },
            { note: "D4", duration: 1, lyric: "what" },
            { note: "D4", duration: 1, lyric: "you" },
            { note: "C4", duration: 2, lyric: "are" }
        ]
    },
    {
        id: "mary-had-a-little-lamb",
        title: "Mary Had a Little Lamb",
        titleHi: "मेरी का छोटा मेमना",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "Classic nursery rhyme - great for beginners",
        descriptionHi: "क्लासिक नर्सरी राइम - शुरुआत के लिए बढ़िया",
        tags: ["nursery", "kids", "beginner"],
        notes: [
            // Mary had a little lamb
            { note: "E4", duration: 1, lyric: "Ma" },
            { note: "D4", duration: 1, lyric: "ry" },
            { note: "C4", duration: 1, lyric: "had" },
            { note: "D4", duration: 1, lyric: "a" },
            { note: "E4", duration: 1, lyric: "lit" },
            { note: "E4", duration: 1, lyric: "tle" },
            { note: "E4", duration: 2, lyric: "lamb" },
            // Little lamb, little lamb
            { note: "D4", duration: 1, lyric: "Lit" },
            { note: "D4", duration: 1, lyric: "tle" },
            { note: "D4", duration: 2, lyric: "lamb" },
            { note: "E4", duration: 1, lyric: "Lit" },
            { note: "G4", duration: 1, lyric: "tle" },
            { note: "G4", duration: 2, lyric: "lamb" },
            // Mary had a little lamb
            { note: "E4", duration: 1, lyric: "Ma" },
            { note: "D4", duration: 1, lyric: "ry" },
            { note: "C4", duration: 1, lyric: "had" },
            { note: "D4", duration: 1, lyric: "a" },
            { note: "E4", duration: 1, lyric: "lit" },
            { note: "E4", duration: 1, lyric: "tle" },
            { note: "E4", duration: 1, lyric: "lamb" },
            { note: "E4", duration: 1, lyric: "" },
            // Its fleece was white as snow
            { note: "D4", duration: 1, lyric: "Its" },
            { note: "D4", duration: 1, lyric: "fleece" },
            { note: "E4", duration: 1, lyric: "was" },
            { note: "D4", duration: 1, lyric: "white" },
            { note: "C4", duration: 2, lyric: "as" },
            { note: "C4", duration: 2, lyric: "snow" }
        ]
    },

    // ===== PUBLIC DOMAIN CLASSICS & FOLK SONGS (FULL) =====
    {
        id: "ode-to-joy",
        title: "Ode to Joy",
        titleHi: "ओड टू जॉय",
        artist: "Ludwig van Beethoven",
        difficulty: "easy",
        instrument: "piano",
        description: "Famous theme from Symphony No. 9",
        descriptionHi: "बीथोवेन की प्रसिद्ध धुन",
        tags: ["classic", "masterpiece", "beginner"],
        notes: [
            { note: "E4", duration: 1, lyric: "Joy" },
            { note: "E4", duration: 1, lyric: "bright" },
            { note: "F4", duration: 1, lyric: "spark" },
            { note: "G4", duration: 1, lyric: "of" },
            { note: "G4", duration: 1, lyric: "di" },
            { note: "F4", duration: 1, lyric: "vin" },
            { note: "E4", duration: 1, lyric: "i" },
            { note: "D4", duration: 1, lyric: "ty" },
            { note: "C4", duration: 1, lyric: "Daugh" },
            { note: "C4", duration: 1, lyric: "ter" },
            { note: "D4", duration: 1, lyric: "of" },
            { note: "E4", duration: 1, lyric: "E" },
            { note: "E4", duration: 1.5, lyric: "ly" },
            { note: "D4", duration: 0.5, lyric: "si" },
            { note: "D4", duration: 2, lyric: "um" },
            // Repeat
            { note: "E4", duration: 1, lyric: "Joy" },
            { note: "E4", duration: 1, lyric: "bright" },
            { note: "F4", duration: 1, lyric: "spark" },
            { note: "G4", duration: 1, lyric: "of" },
            { note: "G4", duration: 1, lyric: "di" },
            { note: "F4", duration: 1, lyric: "vin" },
            { note: "E4", duration: 1, lyric: "i" },
            { note: "D4", duration: 1, lyric: "ty" },
            { note: "C4", duration: 1, lyric: "Daugh" },
            { note: "C4", duration: 1, lyric: "ter" },
            { note: "D4", duration: 1, lyric: "of" },
            { note: "E4", duration: 1, lyric: "E" },
            { note: "D4", duration: 1.5, lyric: "ly" },
            { note: "C4", duration: 0.5, lyric: "si" },
            { note: "C4", duration: 2, lyric: "um" }
        ]
    },
    {
        id: "jingle-bells",
        title: "Jingle Bells",
        titleHi: "जिंगल बेल्स",
        artist: "James Lord Pierpont",
        difficulty: "easy",
        instrument: "piano",
        description: "Classic Christmas song chorus",
        descriptionHi: "क्रिसमस का लोकप्रिय गाना",
        tags: ["christmas", "holiday", "beginner"],
        notes: [
            { note: "E4", duration: 1, lyric: "Jin" },
            { note: "E4", duration: 1, lyric: "gle" },
            { note: "E4", duration: 2, lyric: "bells" },
            { note: "E4", duration: 1, lyric: "jin" },
            { note: "E4", duration: 1, lyric: "gle" },
            { note: "E4", duration: 2, lyric: "bells" },
            { note: "E4", duration: 1, lyric: "jin" },
            { note: "G4", duration: 1, lyric: "gle" },
            { note: "C4", duration: 1, lyric: "all" },
            { note: "D4", duration: 0.5, lyric: "the" },
            { note: "E4", duration: 4, lyric: "way" },
            { note: "F4", duration: 1, lyric: "Oh" },
            { note: "F4", duration: 1, lyric: "what" },
            { note: "F4", duration: 1, lyric: "fun" },
            { note: "F4", duration: 1, lyric: "it" },
            { note: "F4", duration: 1, lyric: "is" },
            { note: "E4", duration: 1, lyric: "to" },
            { note: "E4", duration: 1, lyric: "ride" },
            { note: "E4", duration: 0.5, lyric: "in" },
            { note: "E4", duration: 0.5, lyric: "a" },
            { note: "E4", duration: 1, lyric: "one" },
            { note: "D4", duration: 1, lyric: "horse" },
            { note: "D4", duration: 1, lyric: "o" },
            { note: "E4", duration: 1, lyric: "pen" },
            { note: "D4", duration: 2, lyric: "sleigh" },
            { note: "G4", duration: 2, lyric: "hey" }
        ]
    },
    {
        id: "raghupati-raghav",
        title: "Raghupati Raghav Raja Ram",
        titleHi: "रघुपति राघव राजा राम",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "harmonium",
        description: "Popular Bhajan loved by Mahatma Gandhi",
        descriptionHi: "लोकप्रिय भजन",
        tags: ["devotional", "indian", "traditional"],
        notes: [
            { note: "S", duration: 1, lyric: "Ra" },
            { note: "R", duration: 1, lyric: "ghu" },
            { note: "G", duration: 1, lyric: "pa" },
            { note: "S", duration: 1, lyric: "ti" },
            { note: "R", duration: 1, lyric: "Ra" },
            { note: "S", duration: 1, lyric: "ghav" },
            { note: ".N", duration: 1, lyric: "Ra" },
            { note: ".D", duration: 1, lyric: "ja" },
            { note: "S", duration: 2, lyric: "Ram" },
            { note: "G", duration: 1, lyric: "Pa" },
            { note: "G", duration: 1, lyric: "tit" },
            { note: "R", duration: 1, lyric: "Pa" },
            { note: "R", duration: 1, lyric: "van" },
            { note: "S", duration: 1, lyric: "Si" },
            { note: "R", duration: 1, lyric: "ta" },
            { note: "S", duration: 2, lyric: "Ram" }
        ]
    },
    {
        id: "om-jai-jagdish",
        title: "Om Jai Jagdish Hare",
        titleHi: "ॐ जय जगदीश हरे",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "harmonium",
        description: "Famous Hindu Aarti",
        descriptionHi: "प्रसिद्ध आरती",
        tags: ["devotional", "aarti", "traditional"],
        notes: [
            { note: "S", duration: 1, lyric: "Om" },
            { note: "S", duration: 1, lyric: "Jai" },
            { note: "S", duration: 1, lyric: "Jag" },
            { note: "S", duration: 1, lyric: "dish" },
            { note: "R", duration: 1, lyric: "Ha" },
            { note: "S", duration: 1, lyric: "re" },
            { note: "R", duration: 1, lyric: "Swa" },
            { note: "G", duration: 1, lyric: "mi" },
            { note: "M", duration: 1, lyric: "Jai" },
            { note: "M", duration: 1, lyric: "Jag" },
            { note: "G", duration: 1, lyric: "dish" },
            { note: "R", duration: 1, lyric: "Ha" },
            { note: "S", duration: 2, lyric: "re" }
        ]
    },
    {
        id: "achyutam-keshavam",
        title: "Achyutam Keshavam",
        titleHi: "अच्युतम् केशवम्",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Beautiful Krishna Bhajan",
        descriptionHi: "सुंदर कृष्ण भजन",
        tags: ["devotional", "krishna", "meditation"],
        notes: [
            { note: "C4", duration: 0.5, lyric: "Ach" },
            { note: "D4", duration: 0.5, lyric: "yu" },
            { note: "E4", duration: 1, lyric: "tam" },
            { note: "E4", duration: 1, lyric: "Ke" },
            { note: "E4", duration: 0.5, lyric: "sha" },
            { note: "D4", duration: 1, lyric: "vam" },
            { note: "C4", duration: 1, lyric: "Ra" },
            { note: "D4", duration: 0.5, lyric: "ma" },
            { note: "E4", duration: 0.5, lyric: "na" },
            { note: "F4", duration: 1, lyric: "ra" },
            { note: "E4", duration: 0.5, lyric: "ya" },
            { note: "D4", duration: 1, lyric: "nam" }
        ]
    },
    {
        id: "london-bridge",
        title: "London Bridge is Falling Down",
        titleHi: "लंदन ब्रिज",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "Popular nursery rhyme",
        descriptionHi: "लोकप्रिय नर्सरी राइम",
        tags: ["nursery", "kids", "beginner"],
        notes: [
            { note: "G4", duration: 1, lyric: "Lon" },
            { note: "A4", duration: 0.5, lyric: "don" },
            { note: "G4", duration: 0.5, lyric: "Bridge" },
            { note: "F4", duration: 0.5, lyric: "is" },
            { note: "E4", duration: 0.5, lyric: "fal" },
            { note: "F4", duration: 0.5, lyric: "ling" },
            { note: "G4", duration: 1, lyric: "down" },
            { note: "D4", duration: 0.5, lyric: "Fal" },
            { note: "E4", duration: 0.5, lyric: "ling" },
            { note: "F4", duration: 1, lyric: "down" },
            { note: "E4", duration: 0.5, lyric: "Fal" },
            { note: "F4", duration: 0.5, lyric: "ling" },
            { note: "G4", duration: 1, lyric: "down" }
        ]
    },
    {
        id: "row-your-boat",
        title: "Row, Row, Row Your Boat",
        titleHi: "रो, रो, रो योर बोट",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "Simple round song",
        descriptionHi: "सरल गीत",
        tags: ["nursery", "beginner", "round"],
        notes: [
            { note: "C4", duration: 1, lyric: "Row" },
            { note: "C4", duration: 1, lyric: "row" },
            { note: "C4", duration: 0.75, lyric: "row" },
            { note: "D4", duration: 0.25, lyric: "your" },
            { note: "E4", duration: 1, lyric: "boat" },
            { note: "E4", duration: 0.75, lyric: "Gent" },
            { note: "D4", duration: 0.25, lyric: "ly" },
            { note: "E4", duration: 0.75, lyric: "down" },
            { note: "F4", duration: 0.25, lyric: "the" },
            { note: "G4", duration: 2, lyric: "stream" }
        ]
    },
    {
        id: "old-macdonald",
        title: "Old MacDonald Had a Farm",
        titleHi: "ओल्ड मैकडॉनल्ड",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "Fun animal song",
        descriptionHi: "जानवरों का गीत",
        tags: ["nursery", "kids", "animals"],
        notes: [
            { note: "G4", duration: 0.5, lyric: "Old" },
            { note: "G4", duration: 0.5, lyric: "Mac" },
            { note: "G4", duration: 0.5, lyric: "Don" },
            { note: "D4", duration: 0.5, lyric: "ald" },
            { note: "E4", duration: 0.5, lyric: "had" },
            { note: "E4", duration: 0.5, lyric: "a" },
            { note: "D4", duration: 1, lyric: "farm" },
            { note: "E4", duration: 0.5, lyric: "E" },
            { note: "E4", duration: 0.5, lyric: "I" },
            { note: "E4", duration: 0.5, lyric: "E" },
            { note: "D4", duration: 0.5, lyric: "I" },
            { note: "D4", duration: 0.5, lyric: "O" },
            { note: "D4", duration: 1, lyric: "O" }
        ]
    },
    {
        id: "amazing-grace",
        title: "Amazing Grace",
        titleHi: "अमेज़िंग ग्रेस",
        artist: "John Newton",
        difficulty: "medium",
        instrument: "piano",
        description: "Spiritual hymn",
        descriptionHi: "आध्यात्मिक भजन",
        tags: ["classic", "spiritual", "hymn"],
        notes: [
            { note: "D4", duration: 1, lyric: "A" },
            { note: "G4", duration: 2, lyric: "ma" },
            { note: "B4", duration: 0.5, lyric: "zing" },
            { note: "G4", duration: 0.5, lyric: "" },
            { note: "B4", duration: 2, lyric: "Grace" },
            { note: "A4", duration: 1, lyric: "how" },
            { note: "G4", duration: 2, lyric: "sweet" },
            { note: "E4", duration: 1, lyric: "the" },
            { note: "D4", duration: 2, lyric: "sound" }
        ]
    },
    {
        id: "silent-night",
        title: "Silent Night",
        titleHi: "साइलेंट नाइट",
        artist: "Franz Xaver Gruber",
        difficulty: "easy",
        instrument: "piano",
        description: "Peaceful Christmas carol",
        descriptionHi: "शांतिपूर्ण क्रिसमस गीत",
        tags: ["christmas", "classic", "peaceful"],
        notes: [
            { note: "G4", duration: 1.5, lyric: "Si" },
            { note: "A4", duration: 0.5, lyric: "" },
            { note: "G4", duration: 1, lyric: "lent" },
            { note: "E4", duration: 3, lyric: "night" },
            { note: "G4", duration: 1.5, lyric: "Ho" },
            { note: "A4", duration: 0.5, lyric: "" },
            { note: "G4", duration: 1, lyric: "ly" },
            { note: "E4", duration: 3, lyric: "night" },
            { note: "D5", duration: 2, lyric: "All" },
            { note: "D5", duration: 1, lyric: "is" },
            { note: "B4", duration: 3, lyric: "calm" }
        ]
    },
    {
        id: "brahms-lullaby",
        title: "Brahms' Lullaby",
        titleHi: "ब्रम्स की लोरी",
        artist: "Johannes Brahms",
        difficulty: "medium",
        instrument: "piano",
        description: "Famous lullaby melody",
        descriptionHi: "प्रसिद्ध लोरी",
        tags: ["classic", "lullaby", "sleep"],
        notes: [
            { note: "E4", duration: 0.5, lyric: "Lul" },
            { note: "E4", duration: 0.5, lyric: "la" },
            { note: "G4", duration: 2, lyric: "by" },
            { note: "E4", duration: 0.5, lyric: "and" },
            { note: "E4", duration: 0.5, lyric: "good" },
            { note: "G4", duration: 2, lyric: "night" },
            { note: "E4", duration: 0.5, lyric: "In" },
            { note: "G4", duration: 0.5, lyric: "the" },
            { note: "C5", duration: 1, lyric: "skies" },
            { note: "B4", duration: 0.5, lyric: "stars" },
            { note: "A4", duration: 0.5, lyric: "are" },
            { note: "A4", duration: 0.5, lyric: "bright" },
            { note: "G4", duration: 2, lyric: "" }
        ]
    },
    {
        id: "joy-to-the-world",
        title: "Joy to the World",
        titleHi: "जॉय टू द वर्ल्ड",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "Descending scale song",
        descriptionHi: "नीचे उतरते स्वर का गीत",
        tags: ["christmas", "classic", "scale"],
        notes: [
            { note: "C5", duration: 1, lyric: "Joy" },
            { note: "B4", duration: 0.75, lyric: "to" },
            { note: "A4", duration: 0.25, lyric: "the" },
            { note: "G4", duration: 1.5, lyric: "world" },
            { note: "F4", duration: 0.5, lyric: "the" },
            { note: "E4", duration: 1, lyric: "Lord" },
            { note: "D4", duration: 1, lyric: "is" },
            { note: "C4", duration: 2, lyric: "come" }
        ]
    },
    {
        id: "hickory-dickory-dock",
        title: "Hickory Dickory Dock",
        titleHi: "हickory डिकोरी डॉक",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Fun rhythmic song",
        descriptionHi: "लयबद्ध गीत",
        tags: ["nursery", "kids", "rhythm"],
        notes: [
            { note: "D4", duration: 0.5, lyric: "Hic" },
            { note: "E4", duration: 0.5, lyric: "ko" },
            { note: "F4", duration: 1, lyric: "ry" },
            { note: "G4", duration: 0.5, lyric: "dic" },
            { note: "A4", duration: 0.5, lyric: "ko" },
            { note: "F4", duration: 1, lyric: "ry" },
            { note: "D4", duration: 1, lyric: "dock" },
            { note: "F4", duration: 1, lyric: "" }
        ]
    },
    {
        id: "hot-cross-buns",
        title: "Hot Cross Buns",
        titleHi: "हॉट क्रॉस बन्स",
        artist: "Traditional",
        difficulty: "easy",
        instrument: "piano",
        description: "The classic 3-note song",
        descriptionHi: "क्लासिक ३-नोट गीत",
        tags: ["nursery", "beginner", "food"],
        notes: [
            { note: "E4", duration: 1, lyric: "Hot" },
            { note: "D4", duration: 1, lyric: "cross" },
            { note: "C4", duration: 2, lyric: "buns" },
            { note: "E4", duration: 1, lyric: "Hot" },
            { note: "D4", duration: 1, lyric: "cross" },
            { note: "C4", duration: 2, lyric: "buns" },
            { note: "C4", duration: 0.5, lyric: "One" },
            { note: "C4", duration: 0.5, lyric: "a" },
            { note: "D4", duration: 0.5, lyric: "pen" },
            { note: "D4", duration: 0.5, lyric: "ny" },
            { note: "E4", duration: 1, lyric: "Hot" },
            { note: "D4", duration: 1, lyric: "cross" },
            { note: "C4", duration: 2, lyric: "buns" }
        ]
    },
    {
        id: "au-clair-de-la-lune",
        title: "Au Clair de la Lune",
        titleHi: "चांदनी में",
        artist: "Traditional French",
        difficulty: "easy",
        instrument: "piano",
        description: "French folk song",
        descriptionHi: "फ्रेंच लोक गीत",
        tags: ["folk", "french", "beginner"],
        notes: [
            { note: "C4", duration: 1, lyric: "Au" },
            { note: "C4", duration: 1, lyric: "clair" },
            { note: "C4", duration: 1, lyric: "de" },
            { note: "D4", duration: 1, lyric: "la" },
            { note: "E4", duration: 2, lyric: "lu" },
            { note: "D4", duration: 2, lyric: "ne" },
            { note: "C4", duration: 1, lyric: "Mon" },
            { note: "E4", duration: 1, lyric: "a" },
            { note: "D4", duration: 1, lyric: "mi" },
            { note: "D4", duration: 1, lyric: "Pier" },
            { note: "C4", duration: 2, lyric: "rot" }
        ]
    },
    {
        id: "frere-jacques",
        title: "Frère Jacques",
        titleHi: "फ्रेरे जैक्स",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Popular canon song",
        descriptionHi: "कैनन गीत",
        tags: ["folk", "round", "canon"],
        notes: [
            { note: "C4", duration: 1, lyric: "Are" },
            { note: "D4", duration: 1, lyric: "you" },
            { note: "E4", duration: 1, lyric: "sleep" },
            { note: "C4", duration: 1, lyric: "ing" },
            { note: "C4", duration: 1, lyric: "Are" },
            { note: "D4", duration: 1, lyric: "you" },
            { note: "E4", duration: 1, lyric: "sleep" },
            { note: "C4", duration: 1, lyric: "ing" },
            { note: "E4", duration: 1, lyric: "Bro" },
            { note: "F4", duration: 1, lyric: "ther" },
            { note: "G4", duration: 2, lyric: "John" }
        ]
    },
    {
        id: "oh-susanna",
        title: "Oh! Susanna",
        titleHi: "ओ! सुज़ैना",
        artist: "Stephen Foster",
        difficulty: "medium",
        instrument: "piano",
        description: "American folk song",
        descriptionHi: "अमेरिकी लोक गीत",
        tags: ["folk", "country", "classic"],
        notes: [
            { note: "C4", duration: 0.5, lyric: "I" },
            { note: "D4", duration: 0.5, lyric: "come" },
            { note: "E4", duration: 0.5, lyric: "from" },
            { note: "G4", duration: 0.5, lyric: "A" },
            { note: "G4", duration: 0.5, lyric: "la" },
            { note: "A4", duration: 0.5, lyric: "ba" },
            { note: "G4", duration: 0.5, lyric: "ma" },
            { note: "E4", duration: 0.5, lyric: "With" },
            { note: "C4", duration: 0.5, lyric: "a" },
            { note: "D4", duration: 0.5, lyric: "ban" },
            { note: "E4", duration: 0.5, lyric: "jo" },
            { note: "E4", duration: 0.5, lyric: "on" },
            { note: "D4", duration: 0.5, lyric: "my" },
            { note: "C4", duration: 1, lyric: "knee" }
        ]
    },
    {
        id: "when-the-saints",
        title: "When the Saints Go Marching In",
        titleHi: "जब संत मार्च करते हैं",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Gospel jazz standard",
        descriptionHi: "जाज मानक",
        tags: ["jazz", "gospel", "classic"],
        notes: [
            { note: "C4", duration: 0.5, lyric: "Oh" },
            { note: "E4", duration: 0.5, lyric: "when" },
            { note: "F4", duration: 0.5, lyric: "the" },
            { note: "G4", duration: 1.5, lyric: "saints" },
            { note: "C4", duration: 0.5, lyric: "Oh" },
            { note: "E4", duration: 0.5, lyric: "when" },
            { note: "F4", duration: 0.5, lyric: "the" },
            { note: "G4", duration: 1.5, lyric: "saints" },
            { note: "C4", duration: 0.5, lyric: "Oh" },
            { note: "E4", duration: 0.5, lyric: "when" },
            { note: "F4", duration: 0.5, lyric: "the" },
            { note: "G4", duration: 1, lyric: "saints" },
            { note: "E4", duration: 1, lyric: "go" },
            { note: "C4", duration: 1, lyric: "march" },
            { note: "E4", duration: 1, lyric: "ing" },
            { note: "D4", duration: 2, lyric: "in" }
        ]
    },
    {
        id: "yankee-doodle",
        title: "Yankee Doodle",
        titleHi: "यांकी डूडल",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Patriotic classic",
        descriptionHi: "देशभक्ति गीत",
        tags: ["patriotic", "folk", "usa"],
        notes: [
            { note: "G4", duration: 0.5, lyric: "Yan" },
            { note: "G4", duration: 0.5, lyric: "kee" },
            { note: "A4", duration: 0.5, lyric: "Doo" },
            { note: "B4", duration: 0.5, lyric: "dle" },
            { note: "G4", duration: 0.5, lyric: "went" },
            { note: "B4", duration: 0.5, lyric: "to" },
            { note: "A4", duration: 1, lyric: "town" },
            { note: "G4", duration: 0.5, lyric: "A" },
            { note: "D4", duration: 1, lyric: "ri" },
            { note: "D4", duration: 1, lyric: "ding" },
            { note: "G4", duration: 0.5, lyric: "on" },
            { note: "G4", duration: 0.5, lyric: "a" },
            { note: "A4", duration: 1, lyric: "po" },
            { note: "D4", duration: 1, lyric: "ny" }
        ]
    },
    {
        id: "danny-boy",
        title: "Danny Boy",
        titleHi: "डैनी बॉय",
        artist: "Traditional Irish",
        difficulty: "hard",
        instrument: "piano",
        description: "Londonderry Air ballad",
        descriptionHi: "आयरिश गाथागीत",
        tags: ["folk", "irish", "ballad"],
        notes: [
            { note: "D4", duration: 0.5, lyric: "Oh" },
            { note: "E4", duration: 0.5, lyric: "Dan" },
            { note: "F4", duration: 0.5, lyric: "ny" },
            { note: "G4", duration: 2, lyric: "Boy" },
            { note: "G4", duration: 1, lyric: "the" },
            { note: "A4", duration: 0.5, lyric: "pipes" },
            { note: "G4", duration: 0.5, lyric: "the" },
            { note: "F4", duration: 0.5, lyric: "pipes" },
            { note: "D4", duration: 0.5, lyric: "" },
            { note: "C4", duration: 1, lyric: "are" },
            { note: "D4", duration: 2, lyric: "call" },
            { note: "D4", duration: 1, lyric: "ing" }
        ]
    },
    {
        id: "greensleeves",
        title: "Greensleeves",
        titleHi: "ग्रीनस्लीव्स",
        artist: "Traditional English",
        difficulty: "hard",
        instrument: "piano",
        description: "Renaissance folk song",
        descriptionHi: "पुनर्जागरण लोक गीत",
        tags: ["folk", "english", "renaissance"],
        notes: [
            { note: "A4", duration: 1, lyric: "A" },
            { note: "C5", duration: 2, lyric: "las" },
            { note: "D5", duration: 1, lyric: "my" },
            { note: "E5", duration: 1.5, lyric: "love" },
            { note: "F5", duration: 0.5, lyric: "you" },
            { note: "E5", duration: 1, lyric: "do" },
            { note: "D5", duration: 2, lyric: "me" },
            { note: "B4", duration: 1, lyric: "wrong" },
            { note: "G4", duration: 1.5, lyric: "to" },
            { note: "A4", duration: 0.5, lyric: "cast" },
            { note: "B4", duration: 1, lyric: "me" },
            { note: "C5", duration: 2, lyric: "off" },
            { note: "A4", duration: 1, lyric: "dis" },
            { note: "A4", duration: 1.5, lyric: "cour" },
            { note: "G#4", duration: 0.5, lyric: "teous" },
            { note: "A4", duration: 2, lyric: "ly" }
        ]
    },
    {
        id: "scarborough-fair",
        title: "Scarborough Fair",
        titleHi: "स्कार्बरो मेला",
        artist: "Traditional",
        difficulty: "medium",
        instrument: "piano",
        description: "Haunting English ballad",
        descriptionHi: "अंग्रेजी गाथागीत",
        tags: ["folk", "ballad", "english"],
        notes: [
            { note: "A4", duration: 2, lyric: "Are" },
            { note: "A4", duration: 1, lyric: "you" },
            { note: "E5", duration: 1, lyric: "go" },
            { note: "E5", duration: 1, lyric: "ing" },
            { note: "E5", duration: 1, lyric: "to" },
            { note: "B4", duration: 1, lyric: "Scar" },
            { note: "C5", duration: 1, lyric: "bor" },
            { note: "B4", duration: 1, lyric: "ough" },
            { note: "A4", duration: 3, lyric: "Fair" }
        ]
    },
    {
        id: "bella-ciao",
        title: "Bella Ciao",
        titleHi: "बेला चाओ",
        artist: "Italian Folk",
        difficulty: "medium",
        instrument: "piano",
        description: "Italian protest folk song",
        descriptionHi: "इतालवी लोक गीत",
        tags: ["folk", "italian", "energetic"],
        notes: [
            { note: "A4", duration: 0.5, lyric: "U" },
            { note: "B4", duration: 0.5, lyric: "na" },
            { note: "C5", duration: 0.5, lyric: "mat" },
            { note: "A4", duration: 0.5, lyric: "ti" },
            { note: "B4", duration: 0.5, lyric: "na" },
            { note: "C5", duration: 0.5, lyric: "mi" },
            { note: "A4", duration: 0.5, lyric: "son" },
            { note: "B4", duration: 0.5, lyric: "sve" },
            { note: "C5", duration: 1, lyric: "glia" },
            { note: "A4", duration: 0.5, lyric: "to" },
            { note: "A4", duration: 0.5, lyric: "Oh" },
            { note: "A4", duration: 0.5, lyric: "bel" },
            { note: "D5", duration: 0.5, lyric: "la" },
            { note: "C5", duration: 0.5, lyric: "ciao" },
            { note: "B4", duration: 0.5, lyric: "bel" },
            { note: "A4", duration: 0.5, lyric: "la" },
            { note: "B4", duration: 0.5, lyric: "ciao" },
            { note: "C5", duration: 2, lyric: "ciao" }
        ]
    },
    {
        id: "sakura-sakura",
        title: "Sakura Sakura (Cherry Blossoms)",
        titleHi: "साकुरा",
        artist: "Traditional Japanese",
        difficulty: "medium",
        instrument: "piano",
        description: "Traditional Japanese folk song",
        descriptionHi: "जापानी लोक गीत",
        tags: ["folk", "japanese", "cherry-blossom"],
        notes: [
            { note: "A4", duration: 1, lyric: "Sa" },
            { note: "A4", duration: 1, lyric: "ku" },
            { note: "B4", duration: 1, lyric: "ra" },
            { note: "A4", duration: 1, lyric: "sa" },
            { note: "A4", duration: 1, lyric: "ku" },
            { note: "B4", duration: 2, lyric: "ra" }
        ]
    },
    {
        id: "arirang",
        title: "Arirang",
        titleHi: "अरिरंग",
        artist: "Traditional Korean",
        difficulty: "medium",
        instrument: "piano",
        description: "Korean folk song anthem",
        descriptionHi: "कोरियाई लोक गीत",
        tags: ["folk", "korean", "anthem"],
        notes: [
            { note: "G4", duration: 1.5, lyric: "A" },
            { note: "A4", duration: 0.5, lyric: "ri" },
            { note: "G4", duration: 1, lyric: "rang" },
            { note: "G4", duration: 1, lyric: "A" },
            { note: "A4", duration: 0.5, lyric: "ri" },
            { note: "C5", duration: 1, lyric: "rang" }
        ]
    },
    {
        id: "la-cucaracha",
        title: "La Cucaracha",
        titleHi: "ला कुकाराचा",
        artist: "Traditional Spanish",
        difficulty: "medium",
        instrument: "piano",
        description: "Spanish folk song",
        descriptionHi: "स्पेनिश लोक गीत",
        tags: ["folk", "spanish", "dance"],
        notes: [
            { note: "C4", duration: 0.5, lyric: "La" },
            { note: "C4", duration: 0.5, lyric: "cu" },
            { note: "C4", duration: 0.5, lyric: "ca" },
            { note: "F4", duration: 1, lyric: "ra" },
            { note: "A4", duration: 0.5, lyric: "cha" },
            { note: "C4", duration: 0.5, lyric: "la" },
            { note: "C4", duration: 0.5, lyric: "cu" },
            { note: "C4", duration: 0.5, lyric: "ca" },
            { note: "F4", duration: 1, lyric: "ra" },
            { note: "A4", duration: 1, lyric: "cha" }
        ]
    },
    {
        id: "korobeiniki",
        title: "Korobeiniki (Tetris Theme)",
        titleHi: "टेट्रिस थीम",
        artist: "Russian Folk",
        difficulty: "hard",
        instrument: "piano",
        description: "Famous Russian folk song",
        descriptionHi: "रूसी लोक गीत",
        tags: ["folk", "russian", "game"],
        notes: [
            { note: "E5", duration: 1, lyric: "A" },
            { note: "B4", duration: 0.5, lyric: "" },
            { note: "C5", duration: 0.5, lyric: "B" },
            { note: "D5", duration: 1, lyric: "C" },
            { note: "C5", duration: 0.5, lyric: "D" },
            { note: "B4", duration: 0.5, lyric: "E" },
            { note: "A4", duration: 1, lyric: "F" },
            { note: "A4", duration: 0.5, lyric: "G" },
            { note: "C5", duration: 0.5, lyric: "H" },
            { note: "E5", duration: 1, lyric: "I" },
            { note: "D5", duration: 0.5, lyric: "J" },
            { note: "C5", duration: 0.5, lyric: "K" },
            { note: "B4", duration: 1.5, lyric: "L" }
        ]
    },
    {
        id: "morning-mood",
        title: "Morning Mood",
        titleHi: "मॉर्निंग मूड",
        artist: "Edvard Grieg",
        difficulty: "hard",
        instrument: "piano",
        description: "Peer Gynt Suite No. 1",
        descriptionHi: "पियर गाइंट सुइट",
        tags: ["classic", "grieg", "morning"],
        notes: [
            { note: "G4", duration: 1, lyric: "" },
            { note: "E4", duration: 1, lyric: "" },
            { note: "D4", duration: 1, lyric: "" },
            { note: "C4", duration: 1, lyric: "" },
            { note: "D4", duration: 1, lyric: "" },
            { note: "E4", duration: 1, lyric: "" },
            { note: "G4", duration: 1, lyric: "" },
            { note: "E4", duration: 1, lyric: "" },
            { note: "D4", duration: 1, lyric: "" },
            { note: "C4", duration: 3, lyric: "" }
        ]
    },
    {
        id: "hall-of-mountain-king",
        title: "In the Hall of the Mountain King",
        titleHi: "पर्वत राजा के हॉल में",
        artist: "Edvard Grieg",
        difficulty: "hard",
        instrument: "piano",
        description: "Exciting classical piece",
        descriptionHi: "रोमांचक शास्त्रीय संगीत",
        tags: ["classic", "grieg", "exciting"],
        notes: [
            { note: "B3", duration: 0.5, lyric: "" },
            { note: "C#4", duration: 0.5, lyric: "" },
            { note: "D4", duration: 0.5, lyric: "" },
            { note: "E4", duration: 0.5, lyric: "" },
            { note: "F#4", duration: 0.5, lyric: "" },
            { note: "D4", duration: 0.5, lyric: "" },
            { note: "F#4", duration: 1, lyric: "" },
            { note: "F#4", duration: 1, lyric: "" }
        ]
    },

    // ===== BOLLYWOOD HITS (FULL) =====
    {
        id: "tum-hi-ho",
        title: "Tum Hi Ho (Aashiqui 2)",
        titleHi: "तुम ही हो",
        artist: "Arijit Singh",
        difficulty: "medium",
        instrument: "piano",
        description: "Soulful romantic anthem",
        descriptionHi: "भावपूर्ण रोमांटिक गीत",
        tags: ["bollywood", "romantic", "arijit"],
        notes: [
            // Hum tere bin ab reh nahi sakte
            { note: "G4", duration: 0.5, lyric: "Hum" },
            { note: "A4", duration: 0.5, lyric: "te" },
            { note: "G4", duration: 0.5, lyric: "re" },
            { note: "F4", duration: 0.5, lyric: "bin" },
            { note: "E4", duration: 0.5, lyric: "ab" },
            { note: "F4", duration: 0.5, lyric: "reh" },
            { note: "G4", duration: 1, lyric: "nahi" },
            { note: "F4", duration: 1, lyric: "sak" },
            { note: "E4", duration: 2, lyric: "te" },
            // Tere bina kya wajood mera
            { note: "E4", duration: 0.5, lyric: "Te" },
            { note: "F4", duration: 0.5, lyric: "re" },
            { note: "E4", duration: 0.5, lyric: "bi" },
            { note: "D4", duration: 0.5, lyric: "na" },
            { note: "C4", duration: 0.5, lyric: "kya" },
            { note: "D4", duration: 0.5, lyric: "wa" },
            { note: "E4", duration: 1, lyric: "jood" },
            { note: "D4", duration: 1, lyric: "me" },
            { note: "C4", duration: 2, lyric: "ra" },
            // Tujhse juda gar ho jayenge
            { note: "G4", duration: 0.5, lyric: "Tujh" },
            { note: "A4", duration: 0.5, lyric: "se" },
            { note: "G4", duration: 0.5, lyric: "ju" },
            { note: "F4", duration: 0.5, lyric: "da" },
            { note: "E4", duration: 0.5, lyric: "gar" },
            { note: "F4", duration: 0.5, lyric: "ho" },
            { note: "G4", duration: 1, lyric: "ja" },
            { note: "F4", duration: 1, lyric: "yen" },
            { note: "E4", duration: 2, lyric: "ge" },
            // Toh khud se hi ho jayenge juda
            { note: "E4", duration: 0.5, lyric: "Toh" },
            { note: "F4", duration: 0.5, lyric: "khud" },
            { note: "E4", duration: 0.5, lyric: "se" },
            { note: "D4", duration: 0.5, lyric: "hi" },
            { note: "C4", duration: 0.5, lyric: "ho" },
            { note: "D4", duration: 0.5, lyric: "ja" },
            { note: "E4", duration: 1, lyric: "yen" },
            { note: "D4", duration: 1, lyric: "ge" },
            { note: "C4", duration: 2, lyric: "ju" },
            { note: "B3", duration: 2, lyric: "da" },
            // Kyunki tum hi ho
            { note: "C4", duration: 1, lyric: "Kyun" },
            { note: "D4", duration: 1, lyric: "ki" },
            { note: "E4", duration: 2, lyric: "tum" },
            { note: "F4", duration: 1, lyric: "hi" },
            { note: "G4", duration: 3, lyric: "ho" }
        ]
    },
    {
        id: "kal-ho-naa-ho",
        title: "Kal Ho Naa Ho",
        titleHi: "कल हो ना हो",
        artist: "Sonu Nigam",
        difficulty: "medium",
        instrument: "piano",
        description: "Timeless melody about life",
        descriptionHi: "जीवन के बारे में कालातीत धुन",
        tags: ["bollywood", "classic", "emotional"],
        notes: [
            // Har ghadi badal rahi hai
            { note: "C4", duration: 0.5, lyric: "Har" },
            { note: "C4", duration: 0.5, lyric: "gha" },
            { note: "E4", duration: 1, lyric: "di" },
            { note: "D4", duration: 0.5, lyric: "ba" },
            { note: "D4", duration: 0.5, lyric: "dal" },
            { note: "F4", duration: 1, lyric: "ra" },
            { note: "E4", duration: 0.5, lyric: "hi" },
            { note: "E4", duration: 0.5, lyric: "hai" },
            // Roop zindagi
            { note: "G4", duration: 1, lyric: "roop" },
            { note: "F4", duration: 1, lyric: "zin" },
            { note: "E4", duration: 0.5, lyric: "da" },
            { note: "D4", duration: 2, lyric: "gi" },
            // Chaav hai kabhi
            { note: "C4", duration: 0.5, lyric: "Chaav" },
            { note: "C4", duration: 0.5, lyric: "hai" },
            { note: "E4", duration: 1, lyric: "ka" },
            { note: "D4", duration: 1, lyric: "bhi" },
            // Kabhi hai dhoop zindagi
            { note: "D4", duration: 0.5, lyric: "ka" },
            { note: "D4", duration: 0.5, lyric: "bhi" },
            { note: "F4", duration: 1, lyric: "hai" },
            { note: "E4", duration: 1, lyric: "dhoop" },
            { note: "G4", duration: 1, lyric: "zin" },
            { note: "F4", duration: 1, lyric: "da" },
            { note: "E4", duration: 0.5, lyric: "gi" },
            { note: "D4", duration: 2, lyric: "gi" },
            // Har pal yahan
            { note: "G4", duration: 1, lyric: "Har" },
            { note: "C5", duration: 1, lyric: "pal" },
            { note: "B4", duration: 1, lyric: "ya" },
            { note: "A4", duration: 2, lyric: "han" },
            // Jee bhar jiyo
            { note: "G4", duration: 1, lyric: "jee" },
            { note: "C5", duration: 1, lyric: "bhar" },
            { note: "B4", duration: 1, lyric: "ji" },
            { note: "A4", duration: 2, lyric: "yo" },
            // Jo hai sama
            { note: "A4", duration: 1, lyric: "Jo" },
            { note: "D5", duration: 1, lyric: "hai" },
            { note: "C5", duration: 1, lyric: "sa" },
            { note: "B4", duration: 2, lyric: "ma" },
            // Kal ho naa ho
            { note: "G4", duration: 1, lyric: "kal" },
            { note: "F4", duration: 1, lyric: "ho" },
            { note: "E4", duration: 1, lyric: "naa" },
            { note: "D4", duration: 3, lyric: "ho" }
        ]
    },
    {
        id: "jai-ho",
        title: "Jai Ho (Slumdog Millionaire)",
        titleHi: "जय हो",
        artist: "A.R. Rahman",
        difficulty: "hard",
        instrument: "piano",
        description: "Oscar-winning energetic anthem",
        descriptionHi: "ऑस्कर विजेता गीत",
        tags: ["bollywood", "energetic", "ar-rahman"],
        notes: [
            // Jai Ho, Jai Ho
            { note: "C4", duration: 0.5, lyric: "Jai" },
            { note: "D4", duration: 0.5, lyric: "Ho" },
            { note: "O", duration: 0.5 },
            { note: "C4", duration: 0.5, lyric: "Jai" },
            { note: "D4", duration: 0.5, lyric: "Ho" },
            // Aaja aaja jind shamiyane ke tale
            { note: "E4", duration: 0.5, lyric: "Aa" },
            { note: "E4", duration: 0.5, lyric: "ja" },
            { note: "E4", duration: 0.5, lyric: "aa" },
            { note: "E4", duration: 0.5, lyric: "ja" },
            { note: "D4", duration: 0.5, lyric: "jind" },
            { note: "E4", duration: 0.5, lyric: "sha" },
            { note: "F4", duration: 0.5, lyric: "mi" },
            { note: "E4", duration: 0.5, lyric: "ya" },
            { note: "D4", duration: 0.5, lyric: "ne" },
            { note: "C4", duration: 0.5, lyric: "ke" },
            { note: "D4", duration: 0.5, lyric: "ta" },
            { note: "E4", duration: 2, lyric: "le" },
            // Aaja jariwale nile aasman ke tale
            { note: "E4", duration: 0.5, lyric: "Aa" },
            { note: "E4", duration: 0.5, lyric: "ja" },
            { note: "D4", duration: 0.5, lyric: "ja" },
            { note: "E4", duration: 0.5, lyric: "ri" },
            { note: "F4", duration: 0.5, lyric: "wa" },
            { note: "E4", duration: 0.5, lyric: "le" },
            { note: "D4", duration: 0.5, lyric: "ni" },
            { note: "C4", duration: 0.5, lyric: "le" },
            { note: "D4", duration: 0.5, lyric: "aas" },
            { note: "C4", duration: 0.5, lyric: "man" },
            { note: "B3", duration: 0.5, lyric: "ke" },
            { note: "C4", duration: 0.5, lyric: "ta" },
            { note: "D4", duration: 2, lyric: "le" },
            // Jai Ho
            { note: "C4", duration: 1, lyric: "Jai" },
            { note: "E4", duration: 3, lyric: "Ho" }
        ]
    }
];

export function getSong(id: string): Song | undefined {
    return SONGS.find(s => s.id === id);
}

export function getAllSongs(): Song[] {
    return SONGS;
}

export function getSongsByDifficulty(difficulty: "easy" | "medium" | "hard"): Song[] {
    return SONGS.filter(s => s.difficulty === difficulty);
}

export function getSongsByTag(tag: string): Song[] {
    return SONGS.filter(s => s.tags.includes(tag));
}
